export const mySkills = [
  { title: "AWS", icon: "aws" },
  { title: "Azure", icon: "azure" },
  { title: "Cloudflare", icon: "cloudflare" },
  { title: "Jenkins", icon: "jenkins" },
  { title: "GitLab CI", icon: "gitlab" },
  { title: "Ansible", icon: "ansible" },
  { title: "Terraform", icon: "terraform" },
  { title: "Docker", icon: "docker" },
  { title: "Kubernetes", icon: "kubernetes" },
  { title: "Nginx", icon: "nginx" },
  { title: "ArgoCD", icon: "argocd" },
  { title: "Python", icon: "python" },
  { title: "Bash", icon: "bash" },
  { title: "Java", icon: "java" },
  { title: "Linux", icon: "linux" },
  { title: "Git", icon: "git" },
  { title: "GitHub", icon: "gitHub" },
  { title: "VS Code", icon: "vscode" },
];