export const projects = [
  {
    title: "DevOps End-to-End Portfolio",
    slug: "devops-portfolio",
    tagline: "Complete DevOps workflow showcasing VM setup, load balancer configuration, Docker, Kubernetes, and full CI/CD.",
    overview: "Complete DevOps workflow showcasing VM setup, load balancer configuration, Docker containerization, Kubernetes orchestration, and full CI/CD pipeline implementation.",
    features: [
      "Virtual Machine Setup",
      "Load Balancer Configuration",
      "Docker Containerization",
      "Kubernetes Orchestration",
      "CI/CD Pipeline Implementation",
    ],
    techStack: ["Docker", "Kubernetes", "Jenkins", "Nginx", "Linux"],
    challenges: [],
    learnings: [],
    feedback: false,
    links: {
      github: "https://github.com/NilkanthMiyani/devops-portfolio",
      live: "https://github.com/NilkanthMiyani/devops-portfolio",
    },
  },
  {
    title: "Two-Tier AWS Architecture",
    slug: "two-tier-aws",
    tagline: "Infrastructure as Code project deploying a two-tier architecture on AWS using Terraform.",
    overview: "Infrastructure as Code project deploying a two-tier architecture on AWS using Terraform with VPC, subnets, security groups, and auto-scaling configuration.",
    features: [
      "VPC and Subnet Configuration",
      "Security Groups Setup",
      "Auto-Scaling Configuration",
      "Infrastructure as Code",
    ],
    techStack: ["Terraform", "AWS", "VPC", "HCL"],
    challenges: [],
    learnings: [],
    feedback: false,
    links: {
      github: "https://github.com/NilkanthMiyani/terraform-two-tier-aws",
      live: "https://github.com/NilkanthMiyani/terraform-two-tier-aws",
    },
  },
  {
    title: "Node.js Todo App CI/CD",
    slug: "node-todo-cicd",
    tagline: "Full CI/CD pipeline using GitLab CI/CD for a Node.js application.",
    overview: "Full CI/CD pipeline using GitLab CI/CD for a Node.js application with automated build, test, and deployment stages across environments.",
    features: [
      "Automated Build",
      "Automated Testing",
      "Deployment Stages",
      "Multi-environment Support",
    ],
    techStack: ["GitLab CI", "Node.js", "Docker", "EJS"],
    challenges: [],
    learnings: [],
    feedback: false,
    links: {
      github: "https://github.com/NilkanthMiyani/node-todo-cicd",
      live: "https://github.com/NilkanthMiyani/node-todo-cicd",
    },
  },
  {
    title: "Retail Store Microservices",
    slug: "retail-store-microservices",
    tagline: "Microservices application deployed on AWS EKS using Terraform and ArgoCD.",
    overview: "Microservices application deployed on AWS EKS using Terraform for infrastructure provisioning, Docker for containerization, and ArgoCD for GitOps-based delivery.",
    features: [
      "Infrastructure Provisioning",
      "Docker Containerization",
      "GitOps-based Delivery",
      "AWS EKS Deployment",
    ],
    techStack: ["AWS EKS", "Terraform", "ArgoCD", "Java"],
    challenges: [],
    learnings: [],
    feedback: false,
    links: {
      github: "https://github.com/NilkanthMiyani/retail-store-sample-app",
      live: "https://github.com/NilkanthMiyani/retail-store-sample-app",
    },
  },
  {
    title: "Serverless Website Monitor",
    slug: "serverless-website-monitor",
    tagline: "A lightweight, serverless monitoring stack built on AWS Lambda.",
    overview: "A lightweight, serverless monitoring stack built on AWS Lambda for automated website health checks, alerting, and uptime tracking.",
    features: [
      "Automated Website Health Checks",
      "Alerting Mechanism",
      "Uptime Tracking",
      "Serverless Architecture",
    ],
    techStack: ["Python", "AWS Lambda", "Serverless"],
    challenges: [],
    learnings: [],
    feedback: false,
    links: {
      github: "https://github.com/NilkanthMiyani/serverless-website-monitor",
      live: "https://github.com/NilkanthMiyani/serverless-website-monitor",
    },
  },
  {
    title: "VPC Peering with Terraform",
    slug: "vpc-peering-terraform",
    tagline: "AWS VPC peering setup using Terraform.",
    overview: "AWS VPC peering setup using Terraform, enabling secure and private network communication between isolated cloud environments.",
    features: [
      "VPC Peering",
      "Secure Network Communication",
      "Isolated Cloud Environments",
      "Terraform Provisioning",
    ],
    techStack: ["Terraform", "AWS VPC", "HCL"],
    challenges: [],
    learnings: [],
    feedback: false,
    links: {
      github: "https://github.com/NilkanthMiyani/vpc-peering-terraform",
      live: "https://github.com/NilkanthMiyani/vpc-peering-terraform",
    },
  },
];
